import { Metadata } from "next";

export const PUBLIC_URL = "https://frame-airdrop.vercel.app/";
export const POST_URL = PUBLIC_URL + "/api/frame";

const frameMetadata = {
  "fc:frame": "vNext",
  "fc:frame:image": "https://blocklive.io/util/logo.png",
  "fc:frame:button:1": "$ETH",
  "fc:frame:button:2": "$BTC",
  "fc:frame:post_url": POST_URL,
};

export const metadata: Metadata = {
  title: "Frame Airdrop",
  description: "Generated by create next app",
  other: {
    ...frameMetadata,
  },
};

export default function Home() {
  return (
    <>
      <main>Frame Airdrop!</main>
    </>
  );
}
